- hosts: local-dev
  sudo: yes
  user: vagrant
  tasks:
    - name: Install add-apt-repostory
      apt: name=software-properties-common state=latest

    - name: Install Oracle Java 8
      apt: name={{item}} state=latest
      with_items:
        - openjdk-8-jdk
