- hosts: local-dev
  sudo: yes
  user: vagrant
  tasks:
    - name: Download Apache Maven 
      get_url: url=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.3.3/apache-maven-3.3.3-bin.tar.gz dest=/tmp/apache-maven-3.3.3-bin.tar.gz

    - name: Untar Maven 
      shell: chdir=/tmp creates=/opt/apache-maven-3.3.3 tar -zxf apache-maven-3.3.3-bin.tar.gz -C /opt

    - name: Update path for maven use
      shell: export PATH=/opt/apache-maven-3.3.3/bin:$PATH
